export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";
export const DRONE_LOCATION_DATA_REQUEST = "COMMAND/DRONE_LOCATION_DATA_REQUEST";
export const DRONE_LOCATION_DATA_RECEIVED = "EVENT/DRONE_LOCATION_DATA_RECEIVED";
export const CHART_DATA_REQUEST = "COMMAND/CHART_DATA_REQUEST";
export const CHART_DATA_RECEIVED = "EVENT/CHART_DATA_RECEIVED";
